apiVersion: autoscaling/v2beta2
#https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
kind: HorizontalPodAutoscaler
metadata:
  name: codewar-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: codewar-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
